format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[\n](fg:#7C6F64)\
$character
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like ï„   or disable this
# and use the os module below
[username]
show_always = true
style_user = "fg:green"
style_root = "fg:red"
format = '[$user ]($style)'
disabled = false

[character]
format = "$symbol"
success_symbol = '[ğŸ¯ğŸ¯‚ğŸ¯ƒ ](bold green)'
error_symbol = '[ğŸ¯ğŸ¯‚ğŸ¯ƒ ](bold red)'

[directory]
style = "fg:gray"
format = "[ $path ]($style)"
truncation_length = 10
truncation_symbol = "â€¦/"
truncate_to_repo = true

[c]
symbol = "î˜ "
style = "fg:white"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "ïŒˆ"
style = "fg:white"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = "î‰µ "
style = "fg:white"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = "î˜¬ "
style = "fg:white"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = "ï˜"
style = "fg:white"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:yellow"
modified = " ï‘ˆ Ã—${count}"
ahead = " â‡‘ Ã—${count}"
behind = " â‡“ Ã—${count}"
diverged = " â‡‘ Ã—${ahead_count} â‡“ Ã—${behind_count}"
staged = " ïƒ‡ Ã—${count}"
untracked = " ïŸ• Ã—${count}"
stashed = ""
deleted = " ï‡¸ Ã—${count}"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "î˜§ "
style = "fg:white"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "fg:white"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "î· "
style = "fg:white"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "î‰– "
style = "fg:white"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "î˜¤ "
style = "fg:white"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "fg:green"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "ïš¤ "
style = "fg:white"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "î¨"
style = "fg:white"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = "îœ· "
style = "fg:white"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "fg:white"
format = '[ â™¥ $time ]($style)'
