format = """
[ ](bg:#3c3836)\
$os\
$username\
[îƒ„](bg:#504945 fg:#3c3836)\
$directory\
[îƒ„](fg:#504945 bg:#665c54)\
$git_branch\
$git_status\
[îƒ„](fg:#665c54 bg:#7C6F64)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[îƒ„ ](fg:#7C6F64)\
$character
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like ï„   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#3c3836"
style_root = "bg:#3c3836"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#3c3836"
disabled = true # Disabled by default

[character]
format = "$symbol"
success_symbol = '[ğŸ¢– ](bold green)'
error_symbol = '[ğŸ¢– ](bold red)'

[directory]
style = "bg:#504945"
format = "[ $path ]($style)"
truncation_length = 10
truncation_symbol = "â€¦/"
truncate_to_repo = true

[c]
symbol = "î˜ "
style = "bg:#7C6F64"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "ïŒˆ"
style = "bg:#33658A"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = "î‰µ "
style = "bg:#7C6F64"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = "î˜¬ "
style = "bg:#7C6F64"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = "ï˜"
style = "bg:#665c54"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#665c54"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "î˜§ "
style = "bg:#7C6F64"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#7C6F64"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "î· "
style = "bg:#7C6F64"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "î‰– "
style = "bg:#7C6F64"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:#7C6F64"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#7C6F64"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "ïš¤ "
style = "bg:#7C6F64"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "î¨"
style = "bg:#7C6F64"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = "îœ· "
style = "bg:#7C6F64"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ â™¥ $time ]($style)'
